### ISSUE TITLE
'Error: self signed certificate in certificate chain' at the end of step during build

### ISSUE THREAD

**Issue by joyalexandre** [BMuuN/vsts-assemblyinfo-task#126]
We have an error at the end of execution of the Assembly generation for .net framework.
The total elapsed time of the step is 17 seconds and end with an error.

I've updated to the 2.1.92 version before sending this issue.

Here is the logs:
```
##[section]Démarrage : Set Assembly Manifest Data
==============================================================================
Task         : Assembly Info (.Net Framework)
Description  : Set assembly information such as Version, Copyright and Trademark etc.
Version      : 2.1.92
Author       : Bleddyn Richards
Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
==============================================================================
Task Parameters...
Source folder: C:\DevOpsAgent\agent2\_work\34\s
Source files: **\AssemblyInfo.cs,**\AssemblyInfo.vb
Insert attributes: false
File encoding: auto
Write unicode BOM: false
Title: 
Product: 
Description: 
Company: ***
Copyright: Copyright © 2020
Trademark: 
Culture: 
Configuration: release
Assembly version: 1.1.2002.1
Assembly file version: 1.1.2002.1
Informational version: 1.1.2002.1
Log Level: verbose
Fail on Warning: false

Setting .Net Framework assembly info...
Processing: C:\DevOpsAgent\agent2\_work\34\s\Properties\AssemblyInfo.cs
Detected file encoding: utf-8
AssemblyVersion --> 1.1.2002.1
AssemblyFileVersion --> 1.1.2002.1
AssemblyInformationalVersion --> 1.1.2002.1
AssemblyCompany --> ***
AssemblyConfiguration --> release
AssemblyCopyright --> Copyright © 2020
Verify file encoding: iso-8859-1

ApplicationInsights:CorrelationIdManager [ { Error: self signed certificate in certificate chain
      at Error (native)
      at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
      at emitNone (events.js:86:13)
      at TLSSocket.emit (events.js:185:7)
      at TLSSocket._finishInit (_tls_wrap.js:610:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38) code: 'SELF_SIGNED_CERT_IN_CHAIN' } ]
##[section]Finalisation : Set Assembly Manifest Data
```

**Comment by BMuuN** [comment]
Thanks for posting this and apologies the fix didn't work for you.

Does the task complete successfully or is it failing with the error you've mentioned?

**Comment by joyalexandre** [comment]
It complete successfully.

**Comment by BMuuN** [comment]
I'm glad the task is completing successfully for you but I'm not happy there's an error being dumped in the logs.  

I believe what you're seeing is an underlying issue with the Application Insights SDK.  There are several reports about a similar intermittent issue here:  https://github.com/Microsoft/ApplicationInsights-node.js/issues/180

We'll wait and see what the impact is for other users on threads #118 and #121 and go from there.

**Comment by BMuuN** [comment]
I've pushed another change which no longer initialises App Insights if the `Disabled Telemetry` flag is set.  I'm hoping this new version (v2.1.97) will fix your issue 🤞

**Comment by joyalexandre** [comment]
It's working. Thank you for your kind support!
