### ISSUE TITLE
System.Management.Automation.CommandNotFoundException: The term 'attrib' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by mrandroide16** [BMuuN/vsts-assemblyinfo-task#85]

**Comment by BMuuN** [comment]
Hi @mrandroide16, can you provide the build output from the Assembly Info task...

**Comment by mrandroide16** [comment]
Hi @BMuuN, here it is;
2019-02-06T11:33:30.2939602Z ##[section]Starting: Set AssemblyInfo
2019-02-06T11:33:30.3326583Z ==============================================================================
2019-02-06T11:33:30.3326953Z Task         : Assembly Info
2019-02-06T11:33:30.3327204Z Description  : Set assembly information such as Version, Copyright and Trademark etc.
2019-02-06T11:33:30.3327440Z Version      : 1.1.39
2019-02-06T11:33:30.3327679Z Author       : Bleddyn Richards
2019-02-06T11:33:30.3327931Z Help         : [More Information](https://marketplace.visualstudio.com/items?itemName=bleddynrichards.Assembly-Info-Task)
2019-02-06T11:33:30.3328204Z ==============================================================================
2019-02-06T11:33:31.1784332Z Preparing task execution handler.
2019-02-06T11:33:31.8772168Z Executing the powershell script: mypath\_work\_tasks\Assembly-Info-Task_3edc451e-360c-40e5-a221-a42d5c987ab8\1.1.39\ApplyAssemblyInfo.ps1
2019-02-06T11:33:33.8046623Z Validating Version: 1.1.500.1
2019-02-06T11:33:33.8047770Z 
2019-02-06T11:33:33.8048170Z 
2019-02-06T11:33:33.8814164Z Validating File Version: 1.2
2019-02-06T11:33:33.8815477Z 
2019-02-06T11:33:33.8816079Z 
2019-02-06T11:33:33.8876461Z Task Parameters:
2019-02-06T11:33:33.8877546Z 
2019-02-06T11:33:33.8878050Z 
2019-02-06T11:33:33.8884113Z 	Source Directory: mypath\_work\7\s\code\source
2019-02-06T11:33:33.8885192Z 
2019-02-06T11:33:33.8885694Z 
2019-02-06T11:33:33.8986599Z 	Net Framework File: AssemblyInfo.cs
2019-02-06T11:33:33.8987794Z 
2019-02-06T11:33:33.8988302Z 
2019-02-06T11:33:33.9041456Z 	Title: MyCode
2019-02-06T11:33:33.9042435Z 
2019-02-06T11:33:33.9043001Z 
2019-02-06T11:33:33.9119860Z 	Product: MyProduct
2019-02-06T11:33:33.9177265Z 
2019-02-06T11:33:33.9307046Z 
2019-02-06T11:33:33.9449494Z 	Description: This is my testing
2019-02-06T11:33:33.9513630Z 
2019-02-06T11:33:33.9605752Z 
2019-02-06T11:33:33.9829800Z 	Company: some company
2019-02-06T11:33:33.9918206Z 
2019-02-06T11:33:33.9934946Z 
2019-02-06T11:33:33.9935901Z 	Copyright: sdasfdA
2019-02-06T11:33:33.9936353Z 
2019-02-06T11:33:33.9936766Z 
2019-02-06T11:33:33.9937951Z 	Trademark: ASdaSD
2019-02-06T11:33:33.9938435Z 
2019-02-06T11:33:33.9938847Z 
2019-02-06T11:33:33.9939421Z 	Culture: 
2019-02-06T11:33:33.9939869Z 
2019-02-06T11:33:33.9940275Z 
2019-02-06T11:33:33.9940800Z 	Configuration: release
2019-02-06T11:33:33.9941213Z 
2019-02-06T11:33:33.9941658Z 
2019-02-06T11:33:33.9942175Z 	Version: 1.1.500.1
2019-02-06T11:33:33.9942588Z 
2019-02-06T11:33:33.9942988Z 
2019-02-06T11:33:33.9943526Z 	File Version: 1.2
2019-02-06T11:33:33.9943939Z 
2019-02-06T11:33:33.9944339Z 
2019-02-06T11:33:33.9944848Z 	Informational Version: AS
2019-02-06T11:33:33.9945254Z 
2019-02-06T11:33:33.9949490Z 
2019-02-06T11:33:33.9950133Z 	Insert Attributes: True
2019-02-06T11:33:33.9950568Z 
2019-02-06T11:33:33.9950973Z 
2019-02-06T11:33:33.9951568Z Setting .Net Framework assembly info...
2019-02-06T11:33:33.9951990Z 
2019-02-06T11:33:33.9952435Z 
2019-02-06T11:33:34.3044197Z 	...\_work\7\s\code\source\Properties\AssemblyInfo.cs
2019-02-06T11:33:34.3045628Z 
2019-02-06T11:33:34.3046518Z 
2019-02-06T11:33:34.4902812Z ##[error]System.Management.Automation.CommandNotFoundException: The term 'attrib' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
2019-02-06T11:33:34.4931658Z    at System.Management.Automation.CommandDiscovery.LookupCommandInfo(String commandName, CommandTypes commandTypes, SearchResolutionOptions searchResolutionOptions, CommandOrigin commandOrigin, ExecutionContext context)
2019-02-06T11:33:34.4932351Z    at System.Management.Automation.CommandDiscovery.LookupCommandProcessor(String commandName, CommandOrigin commandOrigin, Nullable`1 useLocalScope)
2019-02-06T11:33:34.4932831Z    at System.Management.Automation.ExecutionContext.CreateCommand(String command, Boolean dotSource)
2019-02-06T11:33:34.4937199Z    at System.Management.Automation.PipelineOps.AddCommand(PipelineProcessor pipe, CommandParameterInternal[] commandElements, CommandBaseAst commandBaseAst, CommandRedirection[] redirections, ExecutionContext context)
2019-02-06T11:33:34.4937847Z    at System.Management.Automation.PipelineOps.InvokePipeline(Object input, Boolean ignoreInput, CommandParameterInternal[][] pipeElements, CommandBaseAst[] pipeElementAsts, CommandRedirection[][] commandRedirections, FunctionContext funcContext)
2019-02-06T11:33:34.4938349Z    at System.Management.Automation.Interpreter.ActionCallInstruction`6.Run(InterpretedFrame frame)
2019-02-06T11:33:34.4938751Z    at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
2019-02-06T11:33:34.5420223Z 	AssemblyVersion: 1.1.500.1
2019-02-06T11:33:34.5420585Z 
2019-02-06T11:33:34.5420760Z 
2019-02-06T11:33:34.5540772Z 	AssemblyFileVersion: 1.2
2019-02-06T11:33:34.5542200Z 
2019-02-06T11:33:34.5548184Z 
2019-02-06T11:33:34.5549120Z 	Adding --> AssemblyInformationalVersion: AS
2019-02-06T11:33:34.5549713Z 
2019-02-06T11:33:34.5550204Z 
2019-02-06T11:33:34.5637030Z 	AssemblyInformationalVersion: AS
2019-02-06T11:33:34.5638276Z 
2019-02-06T11:33:34.5639111Z 
2019-02-06T11:33:34.5675545Z 	AssemblyTitle: 
2019-02-06T11:33:34.5675835Z 
2019-02-06T11:33:34.5676010Z 
2019-02-06T11:33:34.5699257Z 	AssemblyProduct: 
2019-02-06T11:33:34.5699535Z 
2019-02-06T11:33:34.5699704Z 
2019-02-06T11:33:34.5708954Z 	AssemblyCompany: 
2019-02-06T11:33:34.5710108Z 
2019-02-06T11:33:34.5710717Z 
2019-02-06T11:33:34.5774133Z 	AssemblyTrademark: ASdaSD
2019-02-06T11:33:34.5776628Z 
2019-02-06T11:33:34.5823227Z 
2019-02-06T11:33:34.5824106Z 	AssemblyDescription: This is my testing
2019-02-06T11:33:34.5824582Z 
2019-02-06T11:33:34.5825007Z 
2019-02-06T11:33:34.5826137Z 	AssemblyConfiguration: release
2019-02-06T11:33:34.5826679Z 
2019-02-06T11:33:34.5827163Z 
2019-02-06T11:33:34.5827701Z 	AssemblyCopyright: sdasfdA
2019-02-06T11:33:34.5828130Z 
2019-02-06T11:33:34.5828544Z 
2019-02-06T11:33:34.6243477Z 	...\_work\7\s\code\source\Properties\AssemblyInfo.cs - Assembly Info Applied
2019-02-06T11:33:34.6244967Z 
2019-02-06T11:33:34.6245655Z 
2019-02-06T11:33:34.6267091Z 
2019-02-06T11:33:34.6267769Z 
2019-02-06T11:33:34.6269620Z 
2019-02-06T11:33:34.6274814Z 
2019-02-06T11:33:34.6281474Z 
2019-02-06T11:33:34.6283640Z 
2019-02-06T11:33:34.6814403Z ##[error]PowerShell script completed with 1 errors.
2019-02-06T11:33:34.6835473Z ##[section]Finishing: Set AssemblyInfo

**Comment by BMuuN** [comment]
From your build output I can see you're running v1.1.39 of the task.  The latest version is v2.0.73.

Could you update the the latest version by following the steps here:
https://github.com/BMuuN/vsts-assemblyinfo-task/wiki/Upgrade-v1-to-v2

**Comment by BMuuN** [comment]
Any joy @mrandroide16 ?  Did you successfully complete the upgrade?

**Comment by BMuuN** [comment]
Closing as this is an old version of the task (v1) which was written in Power Shell, for which the error is related.

The new version of the task is written in Node which is unaffected by the error / issue.
